version: '3'
services:
  web:
    restart: always
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: "mongo"
    deploy:
      update_config:
        delay: 10s
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
